namespace ProcWitness.App;

internal static class UiTranslator
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Tarama"] = "Scan",
        ["Nasıl Kullanılır?"] = "How to Use",
        ["Bilgi"] = "Information",
        ["Süreli Analiz ▼"] = "Timed Analysis ▼",
        ["Prompt Konumu"] = "Prompt Location",
        ["Analizi Aç"] = "Open Analysis",
        ["SÜREÇ"] = "PROCESS",
        ["AĞ"] = "NET",
        ["SKOR"] = "SCORE",
        ["RİSK"] = "RISK",
        ["YAYINCI"] = "PUBLISHER",
        ["BULGULAR"] = "FINDINGS",
        ["SÜRELİ ANALİZ RAPORU"] = "TIMED ANALYSIS REPORT",
        ["5 ADIMDA PROCWITNESS"] = "PROCWITNESS IN 5 STEPS",
        ["Tarama ve AI raporu için kısa kullanım rehberi"] = "Quick guide to scanning and AI reports",
        ["PROCWITNESS TEKNİK REHBERİ"] = "PROCWITNESS TECHNICAL GUIDE",
        ["Analiz süresini seçin"] = "Choose analysis duration",
        ["Seçimden sonra pencere kapanır ve geri sayım Şimdi Tara düğmesinde görünür."] = "The menu closes after selection and the countdown appears on Scan Now.",
        ["1 dakika"] = "1 minute",
        ["5 dakika"] = "5 minutes",
        ["10 dakika"] = "10 minutes",
        ["20 dakika"] = "20 minutes",
        ["Başlat"] = "Start",
        ["Veri klasörünü aç"] = "Open Data Folder",
        ["01 • VERİ TOPLAMA"] = "01 • DATA COLLECTION",
        ["02 • AĞ GÖZLEMİ"] = "02 • NETWORK OBSERVATION",
        ["03 • SÜRELİ DİNLEME"] = "03 • TIMED MONITORING",
        ["04 • DAVRANIŞ MOTORU"] = "04 • BEHAVIOR ENGINE",
        ["05 • AKILLI FİLTRE"] = "05 • SMART FILTER",
        ["06 • RAPOR ÇIKTILARI"] = "06 • REPORT OUTPUTS",
        ["07 • CANLI RİSK PUANLAMA"] = "07 • LIVE RISK SCORING",
        ["08 • ZAMAN SERİSİ VE KORELASYON"] = "08 • TIME SERIES AND CORRELATION",
        ["09 • MINER / KAÇINMA TESPİTİ"] = "09 • MINER / EVASION DETECTION",
        ["10 • AĞ VE VERİ AKIŞI"] = "10 • NETWORK AND DATA FLOW",
        ["11 • AI VERİ PAKETİ"] = "11 • AI EVIDENCE PACKAGE",
        ["12 • MAHREMİYET VE SINIRLAR"] = "12 • PRIVACY AND LIMITS",
        ["1 • ŞİMDİ TARA  "] = "1 • SCAN NOW  ",
        ["2 • SÜRELİ DİNLE  "] = "2 • TIMED MONITORING  ",
        ["3 • YEREL RAPORU OKU  "] = "3 • READ THE LOCAL REPORT  ",
        ["4 • PROMPTU KOPYALA  "] = "4 • COPY THE PROMPT  ",
        ["5 • GÜVENLİ DOĞRULA  "] = "5 • VERIFY SAFELY  ",
        ["Tarama sekmesindeki düğmeye basın. Çalışan süreçler yerel olarak incelenir. Bir süreci seçerek yolunu, SHA-256 değerini ve yayıncısını görün."] = "Press Scan Now. Running processes are analyzed locally. Select a process to inspect its path, SHA-256 and publisher.",
        ["Süreli Analiz sekmesinden 1, 5, 10, 20 veya özel dakika seçin. Program süre dolana kadar veri toplar. Miner ve aralıklı casus yazılım davranışları için 10–20 dakika önerilir."] = "Choose 1, 5, 10, 20 or custom minutes. The app collects evidence for the full interval. Use 10–20 minutes for miners and intermittent spyware behavior.",
        ["Süre bitince önemsiz ve kararlı süreçler elenir. Yüksek puan kesin zararlı demek değildir; önce incelenmesi gereken adayı gösterir."] = "Stable low-value processes are filtered when the timer ends. A high score is an investigation priority, not proof of malware.",
        ["Analiz için prompt oluştur düğmesine basın. Düğme yeşile döner ve kopyalandığını bildirir. Promptu Codex veya başka bir AI’a yapıştırın."] = "Click Copy Prompt. The button turns green and confirms the copy. Paste it into Codex or another AI.",
        ["AI dosya isterse promptta yolu yazan analysis-*.json dosyasını yükleyin. Yol, yayıncı ve SHA-256 değerini doğrulamadan dosya silmeyin veya süreç sonlandırmayın."] = "If the AI requests evidence, attach the referenced analysis-*.json file. Verify path, publisher and SHA-256 before deleting files or stopping processes.",
        ["• Sürekli veya aniden yükselen CPU\n• Penceresiz yoğun çalışma\n• Yeni / yazılabilir dizindeki dosyalar\n• İmza + ağ bağlantısı birleşimi\n• Yeniden doğan PID ve sıra dışı trafik"] = "• Sustained or suddenly rising CPU\n• Heavy work without a visible window\n• New files in writable locations\n• Signature + network combinations\n• PID respawning and unusual traffic",
        ["• Kronolojik telemetry.jsonl\n• Korelasyonlu analysis-*.json\n• Yerel okunabilir özet\n• Panoya hazır AI promptu\n• Dosya yolu + SHA-256 ile inceleme adayı"] = "• Chronological telemetry.jsonl\n• Correlated analysis-*.json\n• Human-readable local summary\n• Clipboard-ready AI prompt\n• Investigation candidates with path + SHA-256",
        ["• 0–14 Temiz  • 15–29 Düşük\n• 30–54 Orta  • 55–79 Yüksek\n• 80–100 Kritik\n• CPU ≥ %35 ve ≥ %70 ayrı eşiklerdir\n• Tek sinyal değil, birleşik bulgular puanlanır"] = "• 0–14 Clean  • 15–29 Low\n• 30–54 Medium  • 55–79 High\n• 80–100 Critical\n• CPU ≥ 35% and ≥ 70% are separate thresholds\n• Combined findings—not one signal—set the score",
        ["• Örnekler ad + yol + SHA-256 ile birleşir\n• Ortalama / tepe / CPU aralığı hesaplanır\n• Tepe RAM ve ilk–son görülme tutulur\n• Farklı PID sayısı ve yeniden doğuş izlenir\n• Örnek: %5 → uzun süre %90 davranışı yakalanır"] = "• Samples correlate by name + path + SHA-256\n• Average, peak and CPU range are calculated\n• Peak RAM and first/last seen are retained\n• PID count and respawning are tracked\n• Example: 5% → sustained 90% behavior is detected",
        ["• Sürekli yüksek CPU + penceresiz çalışma\n• Yazılabilir dizin + doğrulanamayan yayıncı\n• Görev Yöneticisi öncesi 20 sn incelenir\n• Açıldıktan sonraki 15 sn ile karşılaştırılır\n• ≥ %30 yükün %5’e / beşte birine düşmesi işaretlenir"] = "• Sustained high CPU + no visible window\n• Writable location + unverified publisher\n• 20 seconds before Task Manager are analyzed\n• Compared with 15 seconds after launch\n• A ≥30% load dropping to 5% / one fifth is flagged",
        ["• Sayaç farkları PID bazında hesaplanır\n• Upload ≥ 256 KB: anlamlı değişim\n• Upload ≥ 10 MB: yüksek sinyal\n• Download ≥ 25 MB: dikkat sinyali\n• Uzak IP/port ve süreç türü birlikte yorumlanır"] = "• Counter deltas are calculated per PID\n• Upload ≥ 256 KB: meaningful change\n• Upload ≥ 10 MB: strong signal\n• Download ≥ 25 MB: attention signal\n• Remote IP/port and process role are interpreted together",
        ["• Tepe CPU < %15 ve değişim < 12 ise gürültü elenir\n• Ağ / yeni dosya / imza / PID sinyali korunur\n• Adaylar yerel risk skoruyla sıralanır\n• Yalnızca anlamlı zaman noktaları eklenir\n• AI’dan kanıt, belirsizlik ve yanlış pozitif istenir"] = "• Noise is removed when peak CPU <15% and change <12\n• Network, new-file, signature and PID signals remain\n• Candidates are ranked by local risk score\n• Only meaningful time points are included\n• AI must report evidence, uncertainty and false positives",
        ["• PID, süreç adı ve başlangıç zamanı\n• CPU ve fiziksel RAM kullanımı\n• Dosya yolu, oluşturulma zamanı ve SHA-256\n• Windows Authenticode / macOS codesign\n• Ölçülemeyen özellikler risk sayılmaz"] = "• PID, process name and start time\n• CPU and physical RAM usage\n• Executable metadata and SHA-256\n• Windows Authenticode / macOS codesign\n• Unavailable signals never increase risk",
        ["• Windows: ETW upload/download + IP Helper\n• Linux: /proc soket–PID eşleştirmesi\n• macOS: lsof ile etkin TCP uçları\n• Uzak IP ve portlar süreçle ilişkilendirilir\n• Ölçüm yoksa 0 B güvenli kabul edilmez"] = "• Windows: ETW bytes + IP Helper\n• Linux: /proc socket-to-PID mapping\n• macOS: active TCP endpoints via lsof\n• Remote IPs and ports are linked to processes\n• Missing telemetry is never treated as zero traffic",
        ["• 1, 5, 10, 20 veya özel dakika\n• Yaklaşık 4 saniyede bir yeni örnek\n• Canlı geri sayım\n• Eski veriler oturuma karıştırılmaz\n• Yalnızca gerçek başlangıç–bitiş aralığı raporlanır"] = "• 1, 5, 10, 20 or custom minutes\n• New sample about every 4 seconds\n• Live countdown\n• Previous data is excluded\n• Only the exact capture window is reported",
        ["• Sabit ve düşük yük üreten süreçleri eler\n• CPU sıçraması olanları korur\n• Ağ / yeni dosya / imza sinyalini korur\n• PID değişimini gözden kaçırmaz\n• AI’a yalnızca anlamlı adayları verir"] = "• Removes stable low-load noise\n• Keeps CPU spikes\n• Keeps network, new-file and signature signals\n• Preserves PID changes\n• Sends only meaningful candidates to AI",
        ["• Tüm kayıtlar ProcWitness/data içinde yereldir\n• Veriler otomatik olarak internete gönderilmez\n• 256 MB sonrası son 7 gün korunarak sıkıştırılır\n• Dosya silmez, karantinaya almaz, süreç kapatmaz\n• Son karar: hash + yayıncı + antivirüs/EDR"] = "• All evidence stays under ProcWitness/data\n• Nothing is uploaded automatically\n• Above 256 MB, the latest 7 days are retained\n• No deletion, quarantine or process termination\n• Final decision: hash + publisher + antivirus/EDR"
    };

    public static string ToEnglish(string value) => English.TryGetValue(value, out var translated) ? translated : value;
}
